name: Bug report
description: รายงานบั๊กให้ทีมแก้ก่อนจะลามไปโรงอาหาร
title: "[Bug] คำอธิบายสั้นๆ"
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: อาการที่เจอ
      description: บอกให้ชัด เกิดอะไร ควรเกิดอะไร
      placeholder: กดปุ่ม "บันทึก" แล้วหน้าค้าง ไม่ขึ้น Toast...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: ขั้นตอนทำให้เกิดบั๊ก
      description: เขียนเป็นข้อ 1-2-3 ให้คนอื่น reproduce ได้
      placeholder: |
        1. ไปหน้า ... 
        2. กรอก ... 
        3. กด ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: ควรได้ผลลัพธ์แบบไหน
      placeholder: ควรขึ้น "บันทึกสำเร็จ" และรีเฟรชตาราง
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: ได้ผลลัพธ์จริง
      placeholder: หน้าค้าง ไม่ขึ้นอะไร
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: เวอร์ชัน/ENV
      placeholder: 1.0.2 / PROD หรือ DEV
  - type: input
    id: url
    attributes:
      label: URL/หน้าที่เจอ
      placeholder: /mra/forms
  - type: textarea
    id: screenshots
    attributes:
      label: รูป/Log
      description: แนบภาพหรือ log ที่เกี่ยวข้อง
  - type: dropdown
    id: severity
    attributes:
      label: ความรุนแรง
      options: ["P1 - ดับไฟก่อน", "P2 - เร็วหน่อย", "P3 - ว่างค่อยทำ"]
    validations:
      required: true
